### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by MadhavJivrajani** [mailgun/holster#79]
The README seems to have multiple broken links on account of the tag `v3` not existing. And a few of the packages that have been documented in the README, such as `config` don't seem to exist in the repo anymore.

I can send in a PR for this

**Comment by thrawn01** [comment]
PR's are welcome, thanks!

**Comment by cpustejovsky** [comment]
@thrawn01 I made a PR to fix this: https://github.com/mailgun/holster/pull/80
